version: '3.3'
services:
    redis:
        container_name: redis
        image: 'redis:latest'

    rem:
        container_name: rem
        ports:
            - '127.0.0.1:5000:8000'
        environment:
            - REDIS_HOSTNAME=redis
        image: 'rangerdigital/rem:dev'
